### ISSUE TITLE
One or more replica shards...

### ISSUE THREAD

**Issue by juditnovak** [canonical/opensearch-operator#324] opened 2024-06-07 16:29 UTC
## Steps to reproduce

1. _Particularly_ loaded host system
2. Check out `opensearch-dsahboards-operator` and run pipeline:
```
 tox run -e integration -- tests/integration/test_upgrade.py --model testing --keep-models
```

## Expected behavior
No errorrs

## Actual behavior

See attached screenshots. The problem was permanent, the system didn't recover state (as timestamp on the top indicates).

![Screenshot from 2024-06-07 15-31-41](https://github.com/canonical/opensearch-operator/assets/3271248/77cc698d-071f-4616-a8d1-9e1c2931c129)

![Screenshot from 2024-06-07 15-45-11](https://github.com/canonical/opensearch-operator/assets/3271248/fc2cacd3-0abf-43ae-b9c5-c2ef32c226b9)

## Versions

Operating system:  jammy

Juju CLI: 3.1.8-genericlinux-amd64

Juju agent: 3.1.8

Charm revision: Most likely 90 or 99 (in case caching may be applied on charmhub, 98 has a chance too)

LXD: 5.0.3 (?)

## Log output

![Screenshot from 2024-06-07 15-47-50](https://github.com/canonical/opensearch-operator/assets/3271248/340c3d23-5cbe-43b9-a38a-85a8a8f53efd)
![Screenshot from 2024-06-07 15-44-24](https://github.com/canonical/opensearch-operator/assets/3271248/c3e1f02a-1403-4d33-9c2c-dba203c0d123)
![Screenshot from 2024-06-07 15-41-58](https://github.com/canonical/opensearch-operator/assets/3271248/0d00b13e-4888-4454-9729-b35b8999564e)
![Screenshot from 2024-06-07 15-39-24](https://github.com/canonical/opensearch-operator/assets/3271248/b165b639-9c59-4e10-a838-4f13a566e496)
![Screenshot from 2024-06-07 15-36-06](https://github.com/canonical/opensearch-operator/assets/3271248/5cb3c4f3-22c6-45f6-9308-f9ecaaf72144)
![Screenshot from 2024-06-07 15-35-13](https://github.com/canonical/opensearch-operator/assets/3271248/22c2516f-41f6-4f3a-b2b7-c3f6a17fc298)
![Screenshot from 2024-06-07 15-33-37](https://github.com/canonical/opensearch-operator/assets/3271248/f363fb2e-08fb-43e2-8c85-509266b27d20)
![Screenshot from 2024-06-07 15-21-01](https://github.com/canonical/opensearch-operator/assets/3271248/f01959fb-f5a7-4809-9261-8dc687a73689)

**Comment by phvalguima** [comment] 2024-06-10 17:57
I am seeing the same problem with upgrades. I believe this is caused by GH runner disk usage and opensearch's disk watermark threshold when allocating unassigned shards. Check this comment: https://github.com/canonical/opensearch-operator/pull/319#issuecomment-2156177690

**Comment by phvalguima** [comment] 2024-06-14 10:27
Sorry, the merge above should've not close this issue. I want to investigate it further.

**Comment by phvalguima** [comment] 2024-06-20 13:12
Hi @juditnovak I tried twice this test scenario and cannot reproduce it in my own machine. If you are able to reproduce, can you provide two information:
1. Shard status: `curl -sk -u admin:<PWD> https://<IP>:9200/_cat/shards`
2. [Cluster allocation explain](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html), specially for any unassigned shards seen above: `curl -XGET -H 'Content-Type: application/json' -sk -u admin:<PWD> https://<IP>:9200/_cluster/allocation/explain -d '{  "index": "TARGET_INDEX" }'`

**Comment by juditnovak** [comment] 2024-06-25 09:15
Sure, I'll totally do that. I foresee running similar pipelines locally quite a bit, so we can confirm if the issues occurs again.

**Comment by phvalguima** [comment] 2024-06-25 09:17
Thanks @juditnovak. Let's leave this issue open for now, so we can come back here if we ever see this same issue happening somewhere

**Comment by juditnovak** [comment] 2024-08-02 07:57
This issue is still going on as of today (rev 120). It has actually got worse :-( 

- https://github.com/canonical/opensearch-dashboards-operator/actions/runs/10201280129/job/28223807883#step:28:239i
- https://github.com/canonical/opensearch-dashboards-operator/actions/runs/10207818122/job/28243679111#step:26:256

**Comment by juditnovak** [comment] 2024-08-02 10:13
Even worse... IT's happening for 3-unit installations :-( (Latest revision still 120)

https://github.com/canonical/opensearch-dashboards-operator/actions/runs/10212627790/job/28256884240#step:26:112

**Comment by reneradoi** [comment] 2024-08-09 06:54
Was fixed with https://github.com/canonical/opensearch-operator/pull/387, the operator will now wait for all shards to be moved to other nodes before shutting down Opensearch.

**Closed by reneradoi** 2024-08-09 06:54 UTC
Labels: bug
