### ISSUE TITLE
[STABILITY] Opensearch service doesn't come up: Error: 503 Server Error: Service Unavailable for url: https://10.36.58.203:9200/_nodes

### ISSUE THREAD

**Issue by juditnovak** [canonical/opensearch-operator#219] opened 2024-04-11 17:51 UTC
All details can be found on the pipelines where the issue occurs: 

- https://github.com/canonical/opensearch-dashboards-operator/actions/runs/8590250501/job/23537646297#step:21:1001

**Comment by Mehdi-Bendriss** [comment] 2024-05-06 07:28
Closing as cannot reproduce this issue since https://github.com/canonical/opensearch-operator/pull/279

**Closed by Mehdi-Bendriss** 2024-05-06 07:28 UTC
Labels: bug
